### ISSUE TITLE
so库报错了

### ISSUE THREAD

**Issue by wt959790** [williamwen1986/flutter_orm_demo#1]
2019-06-22 19:05:43.246 1117-1117/com.flutter.flutter_reader E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.flutter.flutter_reader, PID: 1117
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.flutter.flutter_reader-1/base.apk"],nativeLibraryDirectories=[/data/app/com.flutter.flutter_reader-1/lib/arm64, /data/app/com.flutter.flutter_reader-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libluaFramework.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.common.luakit.LuaHelper.<clinit>(LuaHelper.java:27)
        at com.common.luakit.LuaHelper.startLuaKit(LuaHelper.java:30)
        at com.orm.flutterormplugin.FlutterOrmPlugin.registerWith(FlutterOrmPlugin.java:27)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)
        at com.flutter.flutter_reader.MainActivity.onCreate(MainActivity.kt:11)
        at android.app.Activity.performCreate(Activity.java:6722)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2887)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2999)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6565)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by wt959790** [comment]
修改 flutter 的 flutter.gradle 不使用 arm64 的 so 库才能运行
